### PR TITLE
Cleaned up the codebase a bit to help aleviate #16

### PR DESCRIPTION
**Pull request by dekomote**
Cleaned up the codebase, pylint now up several points.

I'd strongly suggest for you guys to install pre-commit hooks including black, pylint and trimming whitespace. Also, turn on trimming whitespaces in your editors, you will save a ton of hassle.

It wouldn't hurt having a sane .pylint as most of the warnings you'll now get are things that companies usually skip.

### CODE REVIEW

**Comment by alexandreyy** [comment]
Could you suggest a configuration for our pylint?

**Comment by dekomote** [comment]
Yes. I'll make a PR to master with pylint, as well as isort, and black and everything.

**Comment by alexandreyy** [comment]
@dekomote , could you solve these conflicts?
after that, we can proceed with the MR.

**Comment by dekomote** [comment]
@alexandreyy fixed up the conflicts. Please do another review and then merge away.

**Comment by alexandreyy** [comment]
Shipped. Thanks, @dekomote

**Pull request merged**
