### PR TITLE
Update dependencies, fix some lintings and warnings

### LINKED ISSUE #14: Fix Warnings
Fix code to remove deprecation warnings:
`gcloud-utils/gcloud_utils/dataproc.py:24: DeprecationWarning: invalid escape sequence \W
 self.__pattern = re.compile('[\W_]+')
virtualenvs/gcloud-utils/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
 from google.protobuf.pyext import _message
virtualenvs/gcloud-utils/lib/python3.7/site-packages/google/cloud/iam.py:38: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
 class Policy(collections.MutableMapping)`

### LINKED ISSUE #20: Update Google libraries
Update Google libraries to newest versions and test if all code is properly running.

### PR DESCRIPTION
**Pull request by eulercamposbarros**
Updates Google dependencies.

Fix #14, #20 and partially #16 (protobuffer warnings https://github.com/protocolbuffers/protobuf/issues/5865)

### CODE REVIEW

**Comment by eulercamposbarros** [comment]
@alexandreyy was the version increment correct? I'm not sure if this should be PATCH or a MINOR version increment.

**Comment by alexandreyy** [comment]
It should be a minor increment. Just make sure nothing gets broken with this update.

**Comment by eulercamposbarros** [comment]
@alexandreyy some pylint warnings involved a larger refactor that I think should be made on a new PR.

**Comment by alexandreyy** [comment]
Ok. We already have an issue opened to fix warnings.

**Comment by eulercamposbarros** [comment]
Updated description to link to all issues related. @alexandreyy is there something else you suggest me to do about this PR?

**Comment by alexandreyy** [comment]
> Updated description to link to all issues related. @alexandreyy is there something else you suggest me to do about this PR?

No. Everything seems to be OK. We can ship it. Thanks, @eulercamposbarros !

**Pull request merged**
