### PR TITLE
Add Cloud Functions Support

### PR DESCRIPTION
**Pull request by hericlesme**
## :package: Cloud Functions

- Create/Deploy Function
  - Runtime
    - [x] Python
    - [ ] NodeJS 6/8/10
    - [ ] Go
  - Triggers
    - [x] HTTP Trigger
    - [ ] Google Cloud Storage
    - [ ] Google Cloud Pub/Sub
    - [ ] Other sources (e.g. Firebase)
  - Source
    - [x] Upload URL
    - [ ] Bucket

- Call Function
  - [x] Execute Function

- List/Describe Functions
  - [x] List Functions
  - [x] Describe Functions

> #12

### CODE REVIEW

**Comment by hericlesme** [comment]
@alexandreyy I have listed a few points to implement in this module. Which of these do you consider essential for a "Minimum Viable Product" (MVP) to be merged?

**Comment by alexandreyy** [comment]
@hericlesme The user needs to be able to deploy and execute a function using python. You code seems to cover all these features. What additional changes we need to enable the Python runtime?

**Comment by hericlesme** [comment]
@alexandreyy I can already create functions with Python 3.7 runtime (branch `functions/source`). I'm just making adjustments to support node and go. As soon as I finish, I'll mark this PR ready to review.

**Comment by alexandreyy** [comment]
We can add Go and Node in another issue.
We just need to have the unit tests for this PR.
Then, we can proceed with this review.
Thanks

**Comment by hericlesme** [comment]
@alexandreyy What do you think about leaving unit tests for another PR? I intend to continue contributing and supporting this module. But I'm a little busy until the end of the week.

**Comment by alexandreyy** [comment]
Ok, we can do that @hericlesme .
Thanks for your contribution!

**Pull request merged**
